DWAPlannerROS:
   holonomic_robot: false

   min_rot_vel: 0.8
   max_rot_vel: 2.0

   max_vel_x: 1.0
   min_vel_x: -1.0
   max_trans_vel: 1.0
   min_trans_vel: 0.1

   max_vel_y: 1.0
   min_vel_y: -1.0

   forward_point_distance: 0.010

