<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jedgar">
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>

    <!-- TODO Measure Jedgar -->
    <xacro:property name="BASE_LENGTH" value="0.300" />
    <xacro:property name="BASE_HEIGHT" value="0.050" />
    <xacro:property name="BASE_MASS" value="1.0" />

    <xacro:property name="WHEEL_THICKNESS" value="0.020" />
    <xacro:property name="WHEEL_RADIUS" value="0.075" />

    <xacro:property name="WHEEL_TO_BACK" value="${WHEEL_RADIUS}" />
    <xacro:property name="WHEELBASE" value="0.200" />

    <xacro:property name="WHEEL_MASS" value="1.0" />
    <xacro:property name="WHEEL_MOMENT" value="${WHEEL_MASS/12*(3*WHEEL_RADIUS**2+WHEEL_THICKNESS**2)}" />

    <xacro:macro name="wheel" params="name">
        <link name="${name}">
            <visual>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${WHEEL_THICKNESS}" radius="${WHEEL_RADIUS}"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${WHEEL_THICKNESS}" radius="${WHEEL_RADIUS}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${WHEEL_MASS}"/>
                <inertia ixx="${WHEEL_MOMENT}" iyy="${WHEEL_MOMENT}" izz="${WHEEL_MOMENT}" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
    </xacro:macro>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${BASE_LENGTH} ${WHEELBASE} ${BASE_HEIGHT}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${BASE_LENGTH} ${WHEELBASE} ${BASE_HEIGHT}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${BASE_MASS}"/>
            <inertia
                ixx="${BASE_MASS/12*(BASE_HEIGHT**2+BASE_LENGTH**2)}"
                iyy="${BASE_MASS/12*(WHEELBASE**2+BASE_LENGTH**2)}"
                izz="${BASE_MASS/12*(WHEELBASE**2+BASE_HEIGHT**2)}"
                ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <link name="caster_link">
        <visual>
            <geometry>
                <sphere radius="0.01"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.01"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0"/>
            <inertia
                ixx="0" iyy="0" izz="0"
                ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <xacro:wheel name="left_wheel"/>
    <xacro:wheel name="right_wheel"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-WHEEL_RADIUS}"/>
    </joint>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="${BASE_LENGTH/2} 0 ${-WHEEL_RADIUS + 0.01}"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-BASE_LENGTH/2+WHEEL_TO_BACK} ${WHEELBASE/2} 0"/>
    </joint>

    <transmission name="left_wheel_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-BASE_LENGTH/2+WHEEL_TO_BACK} ${-WHEELBASE/2} 0"/>
    </joint>

    <transmission name="right_wheel_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_wheel_joint">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

</robot>

