<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jedgar">
    <!-- TODO Measure Jedgar -->
    <xacro:property name="BASE_LENGTH" value="1.0" />
    <xacro:property name="BASE_HEIGHT" value="1.0" />

    <xacro:property name="WHEEL_TO_BACK" value="1.0" />
    <xacro:property name="WHEELBASE" value="1.0" />

    <xacro:property name="WHEEL_THICKNESS" value="1.0" />
    <xacro:property name="WHEEL_RADIUS" value="1.0" />

    <xacro:macro name="wheel" params="name">
        <link name="${name}">
            <visual>
                <origin rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${WHEEL_THICKNESS}" radius="${WHEEL_RADIUS}"/>
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${BASE_LENGTH} ${WHEELBASE} ${BASE_HEIGHT}"/>
            </geometry>
        </visual>
    </link>

    <xacro:wheel name="left_wheel"/>
    <xacro:wheel name="right_wheel"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${WHEEL_RADIUS}"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-BASE_LENGTH/2+WHEEL_TO_BACK} ${WHEELBASE/2} 0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${-BASE_LENGTH/2+WHEEL_TO_BACK} ${-WHEELBASE/2} 0"/>
    </joint>

</robot>

